language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: osx
      python: 3.6

install:
  - pip3 install -r requirements.txt
  - python3 setup.py install
  - pip3 install nose

script:
  - nosetests
