language: python
python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - python3 setup.py install
  - python -m nltk.downloader vader_lexicon
  - pip3 install nose

script:
  - nosetests
